### ISSUE TITLE
Crypto Binance API Class

### ISSUE THREAD

**Issue by andrewbishop89** [andrewbishop89/CryptoTradingBotV2#14]
### Feature Description
Implement a class to work with crypto exchanges at a high level.

Binance has a third party `Client` class that can be used to download data and make trades. We will use this as a base and extrapolate to make a higher level API for all API requests not involving real money. The real money components will be done with the existing functions in the master branch.

### Tasks Checklist
- [ ] `MethodFramework` Class contains methods to work with the 3 lower level APIs in a high level way
  - [ ] initialize lower level APIs; `MarketDataAPI`, `TradeAPI`, `AccountDataAPI`
- [ ] `Method4` Class (and every method after) will be a class inherited from `MethodFramework`
  - [ ] only parameter will be the symbol (rest of information should be contained in class)
- [ ] `MarketDataAPI` Class for accessing data downloaded from Binance via the API and websocket
  - [ ] function to return historical kline data
    - [ ] have option to return to `csv` file
    - [ ] have option to return as `DataFrame`
  - [ ] function to connect to data websocket stream and return live kline data
- [ ] `TradeAPI` Class for making trades including `market_buy`, `market_sell`, `limit_buy`, `limit_sell`, etc
  - [ ] contain API keys
- [ ] `AccountDataAPI` Class for accessing account endpoints of Binance API such as account balance, previous trades
- [ ] Async websocket class/function for interacting with websocket data
